---
title: Frontend__PL - blog dla FrontEnd Developerów
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: krzysiek.wielicki@gmail.com
description: Zbiór informacji dla FrontEnd Developerów. Od CSS przez HTML po JavaScript.
permalink: ":title/"
baseurl: ''
url: https://kwielicki.github.io
twitter_username: jekyllrb
github_username: jekyll
author: Krzysztof Wielicki
read__more: Czytaj artykuł
pagination__next: Przejdź do strony
pagination__prev: Wróć do strony
category__label: Kategorie
tags__label: Tagi
about_blog__label: Kilka słów o blogu
comments:
  provider: disqus
disqus:
  short_name: https-kwielicki-github-io
lang: pl_PL
social:
  name: Krzysztof Wielicki
  links:
  - https://www.linkedin.com/in/krzysztof-wielicki-53a5b610a/
  - https://github.com/kwielicki
markdown: kramdown
theme: minima
paginate: 5
paginate_path: "/page/:num"
sass:
  sass_dir: _sass
  style: :compressed
plugins:
- jekyll-feed
- octopress-autoprefixer
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
  ignore:
    envs:
    - local
  blanklines: false
  profile: false
  startings:
  - html
  - head
  - body
